# Define variables for the PHP version and package version numbers
ARG PHP_VERSION=7.4

# Use the official PHP and Apache image as the base image for the specified version
FROM php:${PHP_VERSION}-apache

# Install the necessary packages using apt-get
RUN apt-get update && \
    apt-get install -y \
    libapache2-mod-php${PHP_VERSION} \
    php${PHP_VERSION}-calendar \
    php${PHP_VERSION}-common \
    php${PHP_VERSION}-ctype \
    php${PHP_VERSION}-curl \
    php${PHP_VERSION}-date \
    php${PHP_VERSION}-dom \
    php${PHP_VERSION}-exif \
    php${PHP_VERSION}-ffi \
    php${PHP_VERSION}-fileinfo \
    php${PHP_VERSION}-filter \
    php${PHP_VERSION}-ftp \
    php${PHP_VERSION}-gd \
    php${PHP_VERSION}-gettext \
    php${PHP_VERSION}-hash \
    php${PHP_VERSION}-iconv \
    php${PHP_VERSION}-json \
    php${PHP_VERSION}-libxml \
    php${PHP_VERSION}-mbstring \
    php${PHP_VERSION}-mysqli \
    php${PHP_VERSION}-mysqlnd \
    php${PHP_VERSION}-opcache \
    php${PHP_VERSION}-openssl \
    php${PHP_VERSION}-pcre \
    php${PHP_VERSION}-pdo \
    php${PHP_VERSION}-pdo_mysql \
    php${PHP_VERSION}-pdo_sqlite \
    php${PHP_VERSION}-phar \
    php${PHP_VERSION}-posix \
    php${PHP_VERSION}-readline \
    php${PHP_VERSION}-reflection \
    php${PHP_VERSION}-session \
    php${PHP_VERSION}-shmop \
    php${PHP_VERSION}-simplexml \
    php${PHP_VERSION}-sockets \
    php${PHP_VERSION}-sodium \
    php${PHP_VERSION}-spl \
    php${PHP_VERSION}-sqlite3 \
    php${PHP_VERSION}-standard \
    php${PHP_VERSION}-sysvmsg \
    php${PHP_VERSION}-sysvsem \
    php${PHP_VERSION}-sysvshm \
    php${PHP_VERSION}-tokenizer \
    php${PHP_VERSION}-xml \
    php${PHP_VERSION}-xmlreader \
    php${PHP_VERSION}-xmlwriter \
    php${PHP_VERSION}-xsl \
    php${PHP_VERSION}-zip \
    zlib1g-dev \
    vim \
    nano \
    git \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    zip \
    unzip

# Enable the necessary Apache modules
RUN a2enmod rewrite && \
    a2enmod headers && \
    a2enmod expires

# Copy your application code into the container
COPY . /var/www/html

# Set the working directory to your application code
WORKDIR /var/www/html

# Expose port 80 for HTTP traffic
EXPOSE 80

# Start Apache when the container starts
CMD ["apache2-foreground"]
